version: 2.1
orbs:
  android: circleci/android@3.0.1
jobs:
  build:
    machine:
      image: android:2025.10.1
    steps:
      - checkout
      - run:
          name: Build Android Release
          command: ./gradlew assembleRelease
  deploy:
    machine:
      image: android:2025.10.1
    steps:
      - checkout
      - run:
          name: Deploy to Play Store
          command: |
            echo "$GOOGLE_PLAY_KEY" > /tmp/google-play-key.json
            ./gradlew publishRelease
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build